### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by hajapy** [conda-forge/bottle-feedstock#9]
The package build has failed on master: https://circleci.com/gh/conda-forge/bottle-feedstock/29
This appears to be same reason for this failure: https://github.com/conda-forge/bottle-feedstock/pull/8#partial-pull-merging

**Comment by jakirkham** [comment]
Looks like the [recent build passed]( https://circleci.com/gh/conda-forge/bottle-feedstock/32 ).
